"""
Django settings for Maps project.

Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'k3(1wh#w3(a^v^w9l6p*jsiy8r#ksjn^mq2*ydq@+09o)#fgov'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'viewer',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
<<<<<<< HEAD:Maps/settings.py
    'leaflet',
=======
>>>>>>> 416fa68b9bc0b02eb9208c8b3b34cf1e8ca7a0c3:viewer-app/Maps/settings.py
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'Maps.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Maps.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

# DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#    }
#}

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
<<<<<<< HEAD:Maps/settings.py
=======
<<<<<<< HEAD:viewer-app/Maps/settings.py
        'NAME': 'mapwarper_development',  # Name of your spatial database
        'USER': 'vagrant',   # Database user
        'PASSWORD': 'vagrant',# Database password
#        'HOST': '127.0.0.1',
#        'PORT': '3000',
=======
>>>>>>> 416fa68b9bc0b02eb9208c8b3b34cf1e8ca7a0c3:viewer-app/Maps/settings.py
        'NAME': 'proj123',
        'USER': 'proj123',
        'PASSWORD' : 'proj123',
        'HOST': '127.0.0.1',
        'PORT': '5432',
        'SCHEMAS' : 'nyc',
<<<<<<< HEAD:Maps/settings.py
    }
}

LEAFLET_CONFIG = {
    'SRID': 26918
}
=======
>>>>>>> 67b25a11b70f3ab54a9ee05b91889631affc4490:Maps/settings.py
    }
}

>>>>>>> 416fa68b9bc0b02eb9208c8b3b34cf1e8ca7a0c3:viewer-app/Maps/settings.py
# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
